spring:
  application:
    name: config-client
  profiles:
    active: dev

  config:
    import: "configserver:http://localhost:8888"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8080
custom:
  message: "дефолтное сообщение, если Config Server недоступен"
